#!/usr/bin/env bash
# SAC (sac_cleanrl.py) on the Mini Pi+ Pro back-and-forth task, Sim1 -> Sim2 sweep.
# Mirrors run_minipiall.sh (MPO) so the two are directly comparable.
#
#   Sim1: MiniPiBackAndForth-v0 on ../../sim/assets/hightorque/scene.xml, one run per seed.
#   Sim2: for every (variant, seed), warm-start from that seed's Sim1 weights.pth
#         and continue on an already-generated XML in ../../sim/assets/hightorque/generated/
#         (the same ones MPO used; this script does NOT regenerate them).
#
# NOTE: unlike the MPO script, sac_cleanrl.py always loads the Sim1 replay_buffer
# when given --weights_path (unless --offline_buffer_path is set), so Sim2 here
# starts WITH the Sim1 buffer. sac_cleanrl.py also has no resume-in-place, so
# there is no --resume mode: every launch starts new timestamped runs.
#
# Every seed runs its own pipeline in parallel; once a seed's Sim1 is done, all
# of its Sim2 variants start in parallel. Concurrency is capped at PER_GPU runs
# per GPU (jobs queue for a free slot).
#
# Usage:
#   bash run_minipi_sac.sh                          # sim_then_continual (default): Sim1, then Sim2
#   bash run_minipi_sac.sh sim                      # Sim1 only
#   bash run_minipi_sac.sh sim_continual_learning   # Sim2 only, from the newest Sim1 run per seed
# Logs: ${RUNS_DIR}/logs/<exp_name>_seed<seed>.log

set -euo pipefail
cd "$(dirname "$0")"

RUN_MODE="${1:-sim_then_continual}"
case "${RUN_MODE}" in
    sim|sim_continual_learning|sim_then_continual) ;;
    *)
        echo "Usage: bash run_minipi_sac.sh [sim|sim_continual_learning|sim_then_continual]" >&2
        exit 1
        ;;
esac

# Headless MuJoCo rendering via EGL.
export MUJOCO_GL=egl

PY="${PY:-python3}"
SCRIPT="sac_cleanrl.py"

# ---- edit these ----
GPU_LIST=(2)                 # physical GPU ids (nvidia-smi numbering)
PER_GPU=4                    # max concurrent runs this script starts per GPU
SEEDS=(1 2)
VARIANTS=()                  # empty = all in manifest; e.g. (mini_pi_mass_fric_20 mini_pi_mass_fric_80)
# --------------------

RUNS_DIR="runs/sac_minipi"

SIM1_EXP_NAME="sac_minipi"
SIM1_TOTAL_TIMESTEPS=500000
SIM1_MODEL_PATH="../../sim/assets/hightorque/scene.xml"

SIM2_PREFIX="continual_sac_minipi"   # Sim2 exp_name = ${SIM2_PREFIX}_<variant>
# Steps to train in Sim2 *on top of* Sim1. sac_cleanrl.py continues the step
# counter from weights.pth and stops at --total_timesteps, so Sim2's
# --total_timesteps is set to (Sim1 weights step + SIM2_STEPS).
SIM2_STEPS=1500000

GEN_DIR="../../sim/assets/hightorque/generated"   # variants already generated by the MPO run

COMMON_ARGS=(
    --env_id MiniPiWalk-v0
    --render_mode rgb_array
    --cuda
    --gamma 0.99                 # per step, same as MPO
    --num_envs 1
    --save_every_n_steps 50000
    --capture_video
    --capture_video_steps 1000
    --capture_video_every 50000
)


# Make CUDA ordinals match nvidia-smi indices.
export CUDA_DEVICE_ORDER=PCI_BUS_ID

# MuJoCo's EGL renderer ignores CUDA_VISIBLE_DEVICES and, by default, grabs EGL
# device 0. EGL device order does NOT match nvidia-smi order on this machine, so
# look up the EGL index whose CUDA device == the requested physical GPU.
egl_device_for_gpu() {
    env -u CUDA_VISIBLE_DEVICES PYOPENGL_PLATFORM=egl "${PY}" - "$1" <<'PY'
import ctypes, sys
from mujoco.egl import egl_ext as EGL
gpu = int(sys.argv[1])
gpa = ctypes.CDLL("libEGL.so.1").eglGetProcAddress
gpa.restype, gpa.argtypes = ctypes.c_void_p, [ctypes.c_char_p]
query = ctypes.CFUNCTYPE(ctypes.c_uint, ctypes.c_void_p, ctypes.c_int,
                         ctypes.POINTER(ctypes.c_long))(gpa(b"eglQueryDeviceAttribEXT"))
for i, dev in enumerate(EGL.eglQueryDevicesEXT()):
    cuda_id = ctypes.c_long(-1)
    if query(ctypes.cast(dev, ctypes.c_void_p).value, 0x323A, ctypes.byref(cuda_id)) and cuda_id.value == gpu:
        print(i)
        sys.exit(0)
sys.exit(f"No EGL device found for GPU {gpu}")
PY
}


# =============================================================================
# Helpers
# =============================================================================

# Newest run dir <exp_name>_<date>_seed_<seed>, or empty.
latest_run_dir() {
    local name="$1" seed="$2"
    find "${RUNS_DIR}" -maxdepth 1 -type d -name "${name}_*_seed_${seed}" \
        -printf '%T@ %p\n' 2>/dev/null | sort -nr | head -n 1 | cut -d' ' -f2-
}

# global_step stored in <run_dir>/weights.pth, or empty.
weights_step() {
    local run_dir="$1"
    [[ -n "${run_dir}" && -f "${run_dir}/weights.pth" ]] || return 0
    "${PY}" -c 'import sys, torch; print(torch.load(sys.argv[1], map_location="cpu", weights_only=False)["global_step"])' \
        "${run_dir}/weights.pth"
}

# Run sac_cleanrl.py once a GPU slot is free. Slots are flock'd files, so they
# are shared by every job (and every concurrent launch of this script) and
# released automatically when the job's subshell exits.
#   run_on_gpu <log_file> <sac_cleanrl.py args...>
run_on_gpu() {
    local log_file="$1"; shift
    (
        local gpu="" slot fd
        mkdir -p "${RUNS_DIR}/.gpu_slots"
        while [[ -z "${gpu}" ]]; do
            # Slot-major order: fill slot 0 on every GPU before slot 1.
            for ((slot=0; slot<PER_GPU; slot++)); do
                for g in "${GPU_LIST[@]}"; do
                    exec {fd}> "${RUNS_DIR}/.gpu_slots/gpu${g}_slot${slot}.lock"
                    if flock -n "${fd}"; then gpu="${g}"; break 2; fi
                    exec {fd}>&-
                done
            done
            [[ -n "${gpu}" ]] || sleep 30
        done

        local egl_device
        egl_device="$(egl_device_for_gpu "${gpu}")"
        echo "    -> GPU ${gpu} (EGL device ${egl_device}), log: ${log_file}"
        CUDA_VISIBLE_DEVICES="${gpu}" MUJOCO_EGL_DEVICE_ID="${egl_device}" \
            "${PY}" "${SCRIPT}" "$@" >> "${log_file}" 2>&1
    )
}


# =============================================================================
# Sim1 (one per seed). Sets SIM1_DIR and SIM1_STEP on success.
# =============================================================================

run_sim1() {
    local seed="$1"
    local log_file="${RUNS_DIR}/logs/${SIM1_EXP_NAME}_seed${seed}.log"

    echo "[seed ${seed}] Sim1: starting new run"
    if ! run_on_gpu "${log_file}" \
            --exp_name "${SIM1_EXP_NAME}" --seed "${seed}" \
            --total_timesteps "${SIM1_TOTAL_TIMESTEPS}" \
            --runs_directory "${RUNS_DIR}" \
            --model_path "${SIM1_MODEL_PATH}" \
            "${COMMON_ARGS[@]}"; then
        echo "[seed ${seed}] ERROR: Sim1 failed; see ${log_file}" >&2
        return 1
    fi
    use_latest_sim1 "${seed}"
}

# Newest Sim1 run's weights.pth as it is now (finished or not).
# Sets SIM1_DIR and SIM1_STEP on success.
use_latest_sim1() {
    local seed="$1" dir step
    dir="$(latest_run_dir "${SIM1_EXP_NAME}" "${seed}")"
    step="$(weights_step "${dir}")"
    if [[ -z "${step}" ]]; then
        echo "[seed ${seed}] ERROR: no Sim1 weights.pth found for ${SIM1_EXP_NAME} seed ${seed} in ${RUNS_DIR}" >&2
        return 1
    fi
    SIM1_DIR="${dir}"; SIM1_STEP="${step}"
    echo "[seed ${seed}] Sim1: using ${dir} (step ${step})"
}


# =============================================================================
# Sim2 (one per variant x seed)
# =============================================================================

run_sim2() {
    local variant="$1" seed="$2"
    local name="${SIM2_PREFIX}_${variant}"
    local xml="${GEN_DIR}/${variant}.xml"
    local log_file="${RUNS_DIR}/logs/${name}_seed${seed}.log"
    [[ -f "${xml}" ]] || { echo "[seed ${seed}] ERROR: missing ${xml}" >&2; return 1; }

    local total=$(( SIM1_STEP + SIM2_STEPS ))
    echo "[seed ${seed}] ${variant}: warm start from ${SIM1_DIR} step ${SIM1_STEP}, training to ${total}"
    run_on_gpu "${log_file}" \
        --exp_name "${name}" --seed "${seed}" \
        --total_timesteps "${total}" \
        --runs_directory "${RUNS_DIR}" \
        --model_path "${xml}" \
        --weights_path "${SIM1_DIR}" \
        "${COMMON_ARGS[@]}"
    echo "[seed ${seed}] ${variant}: done"
}


seed_pipeline() {
    local seed="$1"
    if [[ "${RUN_MODE}" == "sim_continual_learning" ]]; then
        use_latest_sim1 "${seed}" || return 1
    else
        run_sim1 "${seed}" || return 1
    fi
    [[ "${RUN_MODE}" == "sim" ]] && return 0

    local pids=() failed=0
    for variant in "${VARIANTS[@]}"; do
        run_sim2 "${variant}" "${seed}" &
        pids+=("$!")
    done
    for pid in "${pids[@]}"; do wait "${pid}" || failed=1; done
    return "${failed}"
}


# =============================================================================
# Main
# =============================================================================

mkdir -p "${RUNS_DIR}/logs"

if [[ ${#VARIANTS[@]} -eq 0 ]]; then
    [[ -f "${GEN_DIR}/manifest.txt" ]] || {
        echo "ERROR: ${GEN_DIR}/manifest.txt not found (run ../../sim/assets/hightorque/make_mini_pi_variants.py once)" >&2
        exit 1
    }
    mapfile -t VARIANTS < "${GEN_DIR}/manifest.txt"
fi

echo "Mode:     ${RUN_MODE}"
echo "Seeds:    ${SEEDS[*]}"
echo "Variants: ${VARIANTS[*]}"
echo "GPUs:     ${GPU_LIST[*]} (max ${PER_GPU} runs each)"

pids=()
for seed in "${SEEDS[@]}"; do
    seed_pipeline "${seed}" &
    pids+=("$!")
done

failed=0
for pid in "${pids[@]}"; do wait "${pid}" || failed=1; done

if [[ "${failed}" -ne 0 ]]; then
    echo "One or more runs failed; see ${RUNS_DIR}/logs/" >&2
    exit 1
fi

echo
echo "============================================================"
echo "All SAC Mini Pi runs finished (mode: ${RUN_MODE})."
echo "Logs: ${RUNS_DIR}/logs/"
echo "============================================================"
